// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {contentgen} from '../models';

export function CopyToClipboard(arg1:string):Promise<string>;

export function ExportDrafts(arg1:Array<contentgen.Draft>):Promise<string>;

export function ExportLog(arg1:string):Promise<string>;

export function Generate(arg1:contentgen.Options):Promise<Array<contentgen.Draft>>;

export function ImportTextFile():Promise<string>;

export function LoadConfig():Promise<contentgen.Options>;

export function LoadContent():Promise<contentgen.Library>;

export function OpenContentDir():Promise<string>;

export function SaveConfig(arg1:contentgen.Options):Promise<string>;

export function SaveContent(arg1:contentgen.Library):Promise<string>;
