// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {account} from '../models';
import {main} from '../models';
import {config} from '../models';

export function ClearAccounts():Promise<Array<account.Account>>;

export function ClearQueue():Promise<void>;

export function CopyToClipboard(arg1:string):Promise<string>;

export function ExportAccountsResult():Promise<string>;

export function ExportLog(arg1:string):Promise<string>;

export function GetPublishResults():Promise<Array<main.PublishResult>>;

export function ImportAccountsFile(arg1:Array<string>):Promise<Array<account.Account>>;

export function ImportAccountsText(arg1:string):Promise<Array<account.Account>>;

export function LoadAccounts():Promise<Array<account.Account>>;

export function LoadConfig():Promise<config.Config>;

export function MarkBadAccount(arg1:number):Promise<Array<account.Account>>;

export function PasteAccountsFromClipboard():Promise<Array<account.Account>>;

export function PausePublish():Promise<void>;

export function RemoveAccount(arg1:number):Promise<Array<account.Account>>;

export function ResumePublish():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<string>;

export function ScanQueue(arg1:Array<string>):Promise<Array<main.QueueItem>>;

export function SelectAccountFiles():Promise<Array<string>>;

export function SelectFiles():Promise<Array<string>>;

export function SelectFolder():Promise<string>;

export function StartPublish(arg1:config.Config):Promise<string>;

export function StopPublish():Promise<void>;

export function TestAccount(arg1:number):Promise<account.Account>;
