// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearQueue() {
  return window['go']['main']['App']['ClearQueue']();
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function ExportLinks(arg1) {
  return window['go']['main']['App']['ExportLinks'](arg1);
}

export function ExportLog(arg1) {
  return window['go']['main']['App']['ExportLog'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanQueue(arg1, arg2) {
  return window['go']['main']['App']['ScanQueue'](arg1, arg2);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartPublish(arg1) {
  return window['go']['main']['App']['StartPublish'](arg1);
}

export function StopPublish() {
  return window['go']['main']['App']['StopPublish']();
}

export function ValidateToken(arg1) {
  return window['go']['main']['App']['ValidateToken'](arg1);
}
