// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAccount(arg1, arg2) {
  return window['go']['main']['App']['CheckAccount'](arg1, arg2);
}

export function ClipboardGetText() {
  return window['go']['main']['App']['ClipboardGetText']();
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function ExportDrafts(arg1) {
  return window['go']['main']['App']['ExportDrafts'](arg1);
}

export function ExportLog(arg1) {
  return window['go']['main']['App']['ExportLog'](arg1);
}

export function Generate(arg1) {
  return window['go']['main']['App']['Generate'](arg1);
}

export function ImportTextFile() {
  return window['go']['main']['App']['ImportTextFile']();
}

export function ListConfigTree() {
  return window['go']['main']['App']['ListConfigTree']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LoadContent() {
  return window['go']['main']['App']['LoadContent']();
}

export function OpenContentDir() {
  return window['go']['main']['App']['OpenContentDir']();
}

export function ReadConfigFile(arg1) {
  return window['go']['main']['App']['ReadConfigFile'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveTemplates(arg1, arg2) {
  return window['go']['main']['App']['SaveTemplates'](arg1, arg2);
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2);
}

export function TestProxy(arg1) {
  return window['go']['main']['App']['TestProxy'](arg1);
}

export function WriteConfigFile(arg1, arg2) {
  return window['go']['main']['App']['WriteConfigFile'](arg1, arg2);
}
