// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';

export function ClearQueue():Promise<void>;

export function CopyToClipboard(arg1:string):Promise<string>;

export function ExportLinks(arg1:Array<string>):Promise<string>;

export function ExportLog(arg1:string):Promise<string>;

export function LoadConfig():Promise<config.Config>;

export function SaveConfig(arg1:config.Config):Promise<string>;

export function ScanQueue(arg1:Array<string>,arg2:string):Promise<Array<main.QueueItem>>;

export function SelectFiles():Promise<Array<string>>;

export function SelectFolder():Promise<string>;

export function StartPublish(arg1:config.Config):Promise<string>;

export function StopPublish():Promise<void>;

export function ValidateToken(arg1:string):Promise<string>;
