// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function ExportDrafts(arg1) {
  return window['go']['main']['App']['ExportDrafts'](arg1);
}

export function ExportLog(arg1) {
  return window['go']['main']['App']['ExportLog'](arg1);
}

export function Generate(arg1) {
  return window['go']['main']['App']['Generate'](arg1);
}

export function ImportTextFile() {
  return window['go']['main']['App']['ImportTextFile']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LoadContent() {
  return window['go']['main']['App']['LoadContent']();
}

export function OpenContentDir() {
  return window['go']['main']['App']['OpenContentDir']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveContent(arg1) {
  return window['go']['main']['App']['SaveContent'](arg1);
}
